"""Extraction recall for the one committed PDF that has no XML twin (#6).

Draft and pre-introduction bills circulate as PDF only, so the PDF reader is the
sole path to their text and nothing cross-checks it. Every other PDF gate here
either compares against the XML of the same version (test_pdf_xml_amount_recall,
the corpus tree gates) or injects sentinels after extraction, which exercises the
diff layer rather than the reader. Neither is available when there is no XML.

114-hr-2029 v4 (Senate reported) is the corpus's only such version: its XML is
deliberately withheld while #434 is open, per the note in tests/corpus_manifest.toml.
That withholding is what makes the version worth gating here -- on any dual-format
version this claim is already made, more thoroughly, by test_pdf_xml_amount_recall.

Two properties keep the fixture honest:

* Its values are transcribed from the RENDERED pages, not from extractor output.
  A fixture generated by the code under test cannot detect that code being wrong;
  it would encode the defect and pass.
* Its clause strings carry trailing context ("MILITARY CONSTRUCTION, ARMY For
  acquisition", not "MILITARY CONSTRUCTION, ARMY"). Matching is substring-based
  against the whole document, so a bare account header is satisfied by a longer
  sibling -- "MILITARY CONSTRUCTION, ARMY NATIONAL GUARD" contains it, and
  "TITLE II" contains "TITLE I". Such an entry cannot fail when its own target
  disappears, which is the failure this module exists to catch.
  test_fixture_clauses_are_not_subsumed keeps that property from regressing.

Scope, stated plainly: the fixture covers Title I (Department of Defense military
construction), printed pages 2-10 of 138. It is a curated recall check on the
money-bearing head of the bill, not a whole-document guarantee.
"""

from __future__ import annotations

import json

import pytest

from deltatrack.diff_bill import extract_amounts
from tests.corpus_paths import DATA_DIR, fixture_path
from tests.pdf_corpus import cached_pages, full_text

FIXTURE_PATH = DATA_DIR / "pdf" / "draft_114hr2029_fixture.json"

FIXTURE = json.loads(FIXTURE_PATH.read_text())


def _document_text(pages) -> str:
    """One whitespace-normalized string, for substring matching of clause text.

    GPO prints wrap mid-clause and wrap headers across two centered lines, so the
    page text carries newlines and runs of spaces where the clause reads as one
    phrase. Collapsing every whitespace run to a single space makes the assertion
    about the words recovered rather than about how the printer broke the line.
    """
    return " ".join(" ".join(page.text.split()) for page in pages)


def _pages():
    return cached_pages(fixture_path(FIXTURE["bill_id"], FIXTURE["version"] + ".pdf"))


def _bill_label() -> str:
    return f"{FIXTURE['bill_id']} {FIXTURE['version']}"


def test_fixture_clauses_are_not_subsumed() -> None:
    """No clause may be a substring of another, and none may repeat.

    A duplicate entry inflates the apparent coverage while asserting nothing new.
    A clause contained in a longer sibling is worse: it passes on the sibling's
    text, so it cannot go red when the thing it names is dropped. Both are fixture
    defects that a green run would never surface, so they are gated here rather
    than left to review.
    """
    clauses = FIXTURE["clauses"]
    duplicates = sorted({c for c in clauses if clauses.count(c) > 1})
    assert not duplicates, f"Duplicate clause entries: {duplicates}"

    subsumed = sorted(
        {a for a in clauses for b in clauses if a != b and a in b},
    )
    assert not subsumed, (
        f"{len(subsumed)} clause(s) are a substring of another entry and so cannot "
        f"fail independently: {subsumed}. Add trailing context to each."
    )


@pytest.mark.slow
def test_draft_extraction_recall_amounts() -> None:
    """Every amount transcribed from the printed page must survive extraction."""
    extracted = set(extract_amounts(full_text(_pages())))

    missing = [amount for amount in FIXTURE["amounts"] if amount not in extracted]
    assert not missing, (
        f"{len(missing)} of {len(FIXTURE['amounts'])} transcribed amount(s) did not "
        f"survive extraction: {missing}. Bill: {_bill_label()}"
    )


@pytest.mark.slow
def test_draft_extraction_recall_clauses() -> None:
    """Every account header and proviso transcribed from the page must survive."""
    text = _document_text(_pages())

    missing = [clause for clause in FIXTURE["clauses"] if clause not in text]
    assert not missing, (
        f"{len(missing)} of {len(FIXTURE['clauses'])} transcribed clause(s) did not "
        f"survive extraction: {missing}. Bill: {_bill_label()}"
    )
