"""The committed reference reports must match what the renderer produces today (#284).

Three rendered HTML files are checked into the repo: the two under `examples/` and the
sample the web app serves from its landing page. All three are produced by hand, by
running `render_examples.py` and copying one of its outputs over the sample, so they fall
behind silently whenever the renderer changes and nobody re-runs it. They had drifted a
month behind before #285 regenerated them, and the full suite stayed green throughout.

These tests close that gap: they re-render from the committed corpus and compare. The
render is deterministic and takes under two seconds, so it runs in the default CI job
rather than behind the `slow` marker. That choice is load-bearing. CI invokes `slow`
tests only by explicit path (`.github/workflows/ci.yml`), so marking these `slow` would
quietly drop them from CI and rebuild the fail-open gap they exist to close.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

import pytest

from scripts import render_examples
from tests.corpus_paths import FIXTURES_DIR

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
SERVED_SAMPLE = ROOT / "web" / "webapp" / "sample" / "example.html"
PDF_EXAMPLE = EXAMPLES / "hr8752_pdf_diff.html"

REGENERATE = "Run `uv run python scripts/render_examples.py` and commit the result."


def _corpus_files() -> list[Path]:
    """Every bill file `render_examples.py` reads, derived from its own spec list.

    Keyed off each spec's declared `formats`: a pair published from XML only must not
    demand a PDF the corpus deliberately doesn't carry (118-hr-4366 has no Senate PDF).
    """
    return [
        FIXTURES_DIR / spec.bill_dir / f"{stem}.{fmt}"
        for spec in render_examples.EXAMPLES_TO_RENDER
        for stem in (spec.v1_filename_stem, spec.v2_filename_stem)
        for fmt in spec.formats
    ]


def _describe_mismatch(committed: Path, fresh: Path) -> str:
    """Point at the first differing line instead of dumping ~900 KB into the report."""
    old = committed.read_text().splitlines()
    new = fresh.read_text().splitlines()
    for n, (a, b) in enumerate(zip(old, new), start=1):
        if a != b:
            return f"first differs at line {n}:\n  committed: {a[:160]}\n  fresh:     {b[:160]}"
    return f"identical for {min(len(old), len(new))} lines, then lengths differ ({len(old)} vs {len(new)})"


def test_example_corpus_files_are_committed():
    """Fail closed if a source bill goes missing, rather than skipping the comparison.

    Without this, deleting a corpus file would turn the render below into an error or a
    skip, and the drift guard would stop guarding without anyone being told.
    """
    missing = [p.relative_to(ROOT) for p in _corpus_files() if not p.exists()]
    assert not missing, f"corpus files render_examples.py needs are missing: {missing}"


def test_committed_examples_match_a_fresh_render(tmp_path, monkeypatch):
    """The files under `examples/` are what the current renderer emits."""
    monkeypatch.setattr(render_examples, "EXAMPLES", tmp_path)
    render_examples.main()

    fresh_files = sorted(tmp_path.glob("*.html"))
    assert fresh_files, "render_examples.main() wrote nothing; the comparison below would vacuously pass"

    for fresh in fresh_files:
        committed = EXAMPLES / fresh.name
        assert committed.exists(), f"{fresh.name} is rendered but not committed. {REGENERATE}"
        if committed.read_bytes() != fresh.read_bytes():
            pytest.fail(f"examples/{fresh.name} is stale. {REGENERATE}\n{_describe_mismatch(committed, fresh)}")


def test_no_committed_example_is_orphaned(tmp_path, monkeypatch):
    """Nothing under `examples/` survives that `render_examples.py` doesn't produce.

    The complement of the test above, and the one that would have caught #42: the check
    that every *rendered* file is committed says nothing about a *committed* file nobody
    renders. Two reports generated by a since-replaced CI invocation and a hand-built
    design mock sat here for months, published to GitHub Pages as the project's demo,
    drifting fifteenfold behind the renderer with the suite green the whole time.
    """
    monkeypatch.setattr(render_examples, "EXAMPLES", tmp_path)
    render_examples.main()

    rendered = {p.name for p in tmp_path.glob("*.html")}
    committed = {p.name for p in EXAMPLES.glob("*.html")}
    orphans = sorted(committed - rendered)
    assert not orphans, (
        f"examples/ carries HTML that render_examples.py does not produce: {orphans}. "
        "Publishing a report the pipeline can no longer regenerate is how the examples "
        "drift from the tool. Either add a spec to EXAMPLES_TO_RENDER or delete the file."
    )


#: A `--name: value` custom-property declaration. Matched rather than split on `;`/`:`,
#: because splitting silently drops the first declaration after `:root {` and any
#: preceded by a comment — a parse gap that reads as "token missing" and would make this
#: gate fail for the wrong reason.
_TOKEN_DECL = re.compile(r"(--[\w-]+)\s*:\s*([^;{}]+)")


#: A `var(--name)` reference, however the reference is spaced.
_VAR_REFERENCE = re.compile(r"var\(\s*(--[\w-]+)")

#: The contents of the report's one `<style>` element, and a `/* ... */` CSS comment.
_STYLE_BLOCK = re.compile(r"<style[^>]*>(.*?)</style>", re.S)
_CSS_COMMENT = re.compile(r"/\*.*?\*/", re.S)


def _css_tokens(css: str) -> dict[str, str]:
    """`--name: value` declarations in a stylesheet fragment, whitespace-normalized."""
    return {name: " ".join(value.split()) for name, value in _TOKEN_DECL.findall(css)}


def _live_stylesheet(html: str) -> str:
    """A rendered report's embedded CSS: `<style>` only, with comments stripped.

    Both narrowings are load-bearing for the palette census below, which reads a
    `var()` as evidence that a token is *used*. Text that never executes as CSS is not
    evidence: a report is mostly bill content, and this stylesheet carries prose
    comments that mention the properties they explain. Counting either lets a dead
    token look used — the exact false green this scoping closes, since the census is
    the only thing standing between the palette and the dead declarations #667 removed.

    Stripping comments before the declarations are read matters too: a `--name: value`
    or a `}` inside a comment would otherwise be taken for a declaration, or truncate
    the `:root` block early.
    """
    return _CSS_COMMENT.sub("", "\n".join(_STYLE_BLOCK.findall(html)))


def _root_block(html: str) -> str:
    """The `:root { ... }` declarations of a rendered report's embedded stylesheet."""
    start = html.index(":root {")
    return html[start : html.index("}", start)]


def test_index_page_tokens_match_the_report_tokens():
    """The landing page and the reports it links use the same palette values.

    Both derive from `deltatrack.palette`, so this compares a *committed rendered report*
    against what that module produces today. It catches the two ways they can still come
    apart: the committed examples going stale against a palette change, or a surface
    ceasing to derive from the module at all. The second is what let the demo's front
    door look like a different product from everything behind it, the mismatch #42 was
    filed over.

    Read from a rendered report rather than the renderer's module, so what a visitor
    actually gets is what is compared.

    History: `INDEX_TOKENS` was a hand-copied subset of the report stylesheet until it
    became generated, and this test existed to keep that copy honest.

    Both sides are read comment-free, for the reason `_live_stylesheet` gives: a value
    kept only in a comment is not the value anything renders with. Since `_css_tokens`
    lets the last declaration win, a commented copy sitting after a changed live one
    would otherwise answer this comparison in its place and hide the drift.
    """
    report_css = _live_stylesheet((EXAMPLES / "hr8752_xml_diff.html").read_text())
    report_tokens = _css_tokens(_root_block(report_css))
    index_tokens = _css_tokens(_CSS_COMMENT.sub("", render_examples.INDEX_TOKENS))

    assert index_tokens, "no tokens parsed from INDEX_TOKENS; this comparison would vacuously pass"
    assert report_tokens, "no tokens parsed from the rendered report; this comparison would vacuously pass"

    mismatched = {
        name: (value, report_tokens.get(name))
        for name, value in index_tokens.items()
        if report_tokens.get(name) != value
    }
    assert not mismatched, (
        "examples/index.html uses palette values that differ from the reports it links "
        f"(name: index value vs report value): {mismatched}. Both should come from "
        "`deltatrack.palette`. Regenerate with `uv run python scripts/render_examples.py` "
        "and commit the result; if that does not clear it, a surface has stopped deriving "
        "from the module."
    )


def test_the_report_palette_declares_exactly_what_it_uses():
    """No token a report declares is unused, and no `var()` it uses is undeclared (#667).

    The palette is DeltaTrack's own and ships in full inside every report, so a token
    nothing references is weight carried by every reader for no effect. Eleven had
    accumulated while the block was held identical to another product's, which is the
    pressure this pins against: the cheapest way to satisfy a copy is to take the whole
    source, and nothing then objects to the parts that style nothing here.

    Read from a *rendered report* rather than `_DESIGN_TOKENS_CSS`, for the same reason
    as the token comparison above — the report is what ships, so the check covers
    anything that reaches the stylesheet, not just the one constant. Narrowed to the
    CSS that actually runs, via `_live_stylesheet`: counting `var()` text from report
    content or a comment would let a dead token pass as used.

    The undeclared half is the safety catch on the unused half: the cheap way to satisfy
    a dead-token check is to delete a token something actually uses, and a `var()` with
    no declaration behind it fails silently in a browser rather than loudly here.
    """
    css = _live_stylesheet((EXAMPLES / "hr8752_pdf_diff.html").read_text())
    declared = set(_css_tokens(_root_block(css)))
    used = set(_VAR_REFERENCE.findall(css))

    assert css, "no <style> block parsed from the rendered report; this check would vacuously pass"
    assert declared, "no tokens parsed from the rendered report; this check would vacuously pass"
    assert used, "no var() references parsed from the rendered report; this check would vacuously pass"

    unused = sorted(declared - used)
    assert not unused, (
        f"the report stylesheet declares tokens nothing references: {unused}. They ship "
        "in every report and style nothing. Either use them or drop them from "
        "`_DESIGN_TOKENS_CSS`."
    )

    undeclared = sorted(used - declared)
    assert not undeclared, (
        f"the report stylesheet uses var() names it never declares: {undeclared}. Each "
        "resolves to nothing when the report is opened, so whatever they style falls "
        "back silently rather than failing here."
    )


_VERSIONS_LINE = re.compile(r'<div class="versions">(.*?)</div>', re.S)


def test_both_pipelines_head_the_same_pair_identically():
    """The XML and PDF reports for HR 8752 label their versions the same way (#42).

    `index.html` invites a reader to open both and see that the pipelines agree, so a
    header that reads `v1: reported-in-house → v2: engrossed-in-house` on one and
    `reported-in-house → engrossed-in-house` on the other undercuts the demo's whole
    claim. Asserted on the rendered files rather than the builders, because the
    version line is assembled from three separate inputs (labels, ordinals, congress)
    and only the end output shows what a reader actually gets.
    """
    heads = {}
    for fmt in ("xml", "pdf"):
        match = _VERSIONS_LINE.search((EXAMPLES / f"hr8752_{fmt}_diff.html").read_text())
        assert match, f"no versions line found in hr8752_{fmt}_diff.html; this check would vacuously pass"
        heads[fmt] = match.group(1).strip()

    assert heads["xml"] == heads["pdf"], (
        f"the two HR 8752 examples label the same version pair differently: "
        f"XML {heads['xml']!r} vs PDF {heads['pdf']!r}. {REGENERATE}"
    )


def test_served_sample_matches_the_pdf_example():
    """The sample the web app serves is a copy of the committed PDF example.

    `web/webapp/index.html` offers "View a sample report", so this file is the first thing a
    visitor opens. `docs/web-compare.md` documents it as a copy of `examples/*_pdf_diff.html`;
    this pins that, so the sample cannot lag the example it is copied from.
    """
    served = hashlib.sha256(SERVED_SAMPLE.read_bytes()).hexdigest()
    example = hashlib.sha256(PDF_EXAMPLE.read_bytes()).hexdigest()
    assert served == example, (
        f"{SERVED_SAMPLE.relative_to(ROOT)} does not match {PDF_EXAMPLE.relative_to(ROOT)} "
        f"({served[:12]} vs {example[:12]}). {REGENERATE} Then copy it over the sample:\n"
        f"  cp {PDF_EXAMPLE.relative_to(ROOT)} {SERVED_SAMPLE.relative_to(ROOT)}"
    )
