"""The committed reference reports must match what the renderer produces today (#284).

Three rendered HTML files are checked into the repo: the two under `examples/` and the
sample the web app serves from its landing page. All three are produced by hand, by
running `render_examples.py` and copying one of its outputs over the sample, so they fall
behind silently whenever the renderer changes and nobody re-runs it. They had drifted a
month behind before #285 regenerated them, and the full suite stayed green throughout.

These tests close that gap: they re-render from the committed corpus and compare. The
render is deterministic and takes under two seconds, so it runs in the default CI job
rather than behind the `slow` marker. That choice is load-bearing. CI invokes `slow`
tests only by explicit path (`.github/workflows/ci.yml`), so marking these `slow` would
quietly drop them from CI and rebuild the fail-open gap they exist to close.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

import pytest

import render_examples
from corpus_paths import FIXTURES_DIR

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
SERVED_SAMPLE = ROOT / "webapp" / "sample" / "example.html"
PDF_EXAMPLE = EXAMPLES / "hr8752_pdf_diff.html"

REGENERATE = "Run `uv run python render_examples.py` and commit the result."


def _corpus_files() -> list[Path]:
    """Every bill file `render_examples.py` reads, derived from its own spec list.

    Keyed off each spec's declared `formats`: a pair published from XML only must not
    demand a PDF the corpus deliberately doesn't carry (118-hr-4366 has no Senate PDF).
    """
    return [
        FIXTURES_DIR / spec.bill_dir / f"{stem}.{fmt}"
        for spec in render_examples.EXAMPLES_TO_RENDER
        for stem in (spec.v1_filename_stem, spec.v2_filename_stem)
        for fmt in spec.formats
    ]


def _describe_mismatch(committed: Path, fresh: Path) -> str:
    """Point at the first differing line instead of dumping ~900 KB into the report."""
    old = committed.read_text().splitlines()
    new = fresh.read_text().splitlines()
    for n, (a, b) in enumerate(zip(old, new), start=1):
        if a != b:
            return f"first differs at line {n}:\n  committed: {a[:160]}\n  fresh:     {b[:160]}"
    return f"identical for {min(len(old), len(new))} lines, then lengths differ ({len(old)} vs {len(new)})"


def test_example_corpus_files_are_committed():
    """Fail closed if a source bill goes missing, rather than skipping the comparison.

    Without this, deleting a corpus file would turn the render below into an error or a
    skip, and the drift guard would stop guarding without anyone being told.
    """
    missing = [p.relative_to(ROOT) for p in _corpus_files() if not p.exists()]
    assert not missing, f"corpus files render_examples.py needs are missing: {missing}"


def test_committed_examples_match_a_fresh_render(tmp_path, monkeypatch):
    """The files under `examples/` are what the current renderer emits."""
    monkeypatch.setattr(render_examples, "EXAMPLES", tmp_path)
    render_examples.main()

    fresh_files = sorted(tmp_path.glob("*.html"))
    assert fresh_files, "render_examples.main() wrote nothing; the comparison below would vacuously pass"

    for fresh in fresh_files:
        committed = EXAMPLES / fresh.name
        assert committed.exists(), f"{fresh.name} is rendered but not committed. {REGENERATE}"
        if committed.read_bytes() != fresh.read_bytes():
            pytest.fail(f"examples/{fresh.name} is stale. {REGENERATE}\n{_describe_mismatch(committed, fresh)}")


def test_no_committed_example_is_orphaned(tmp_path, monkeypatch):
    """Nothing under `examples/` survives that `render_examples.py` doesn't produce.

    The complement of the test above, and the one that would have caught #42: the check
    that every *rendered* file is committed says nothing about a *committed* file nobody
    renders. Two reports generated by a since-replaced CI invocation and a hand-built
    design mock sat here for months, published to GitHub Pages as the project's demo,
    drifting fifteenfold behind the renderer with the suite green the whole time.
    """
    monkeypatch.setattr(render_examples, "EXAMPLES", tmp_path)
    render_examples.main()

    rendered = {p.name for p in tmp_path.glob("*.html")}
    committed = {p.name for p in EXAMPLES.glob("*.html")}
    orphans = sorted(committed - rendered)
    assert not orphans, (
        f"examples/ carries HTML that render_examples.py does not produce: {orphans}. "
        "Publishing a report the pipeline can no longer regenerate is how the examples "
        "drift from the tool. Either add a spec to EXAMPLES_TO_RENDER or delete the file."
    )


#: A `--name: value` custom-property declaration. Matched rather than split on `;`/`:`,
#: because splitting silently drops the first declaration after `:root {` and any
#: preceded by a comment — a parse gap that reads as "token missing" and would make this
#: gate fail for the wrong reason.
_TOKEN_DECL = re.compile(r"(--[\w-]+)\s*:\s*([^;{}]+)")


def _css_tokens(css: str) -> dict[str, str]:
    """`--name: value` declarations in a stylesheet fragment, whitespace-normalized."""
    return {name: " ".join(value.split()) for name, value in _TOKEN_DECL.findall(css)}


def test_index_page_tokens_match_the_report_tokens():
    """The landing page and the reports it links use the same brand values.

    `render_examples.INDEX_TOKENS` is a hand-copied subset of the report stylesheet, so
    it can fall behind a brand change and leave the demo's front door looking like a
    different product than everything behind it — the mismatch #42 was filed over. Read
    from a *rendered report* rather than the module source, so this compares what a
    visitor actually gets. (Upstreaming both to BillTrax is epic #37.)
    """
    report_css = (EXAMPLES / "hr8752_xml_diff.html").read_text()
    report_tokens = _css_tokens(
        report_css[report_css.index(":root {") : report_css.index("}", report_css.index(":root {"))]
    )
    index_tokens = _css_tokens(render_examples.INDEX_TOKENS)

    assert index_tokens, "no tokens parsed from INDEX_TOKENS; this comparison would vacuously pass"
    assert report_tokens, "no tokens parsed from the rendered report; this comparison would vacuously pass"

    mismatched = {
        name: (value, report_tokens.get(name))
        for name, value in index_tokens.items()
        if report_tokens.get(name) != value
    }
    assert not mismatched, (
        "examples/index.html uses brand tokens that differ from the reports it links "
        f"(name: index value vs report value): {mismatched}. Re-copy the values into "
        "render_examples.INDEX_TOKENS and re-run the script."
    )


def test_served_sample_matches_the_pdf_example():
    """The sample the web app serves is a copy of the committed PDF example.

    `webapp/index.html` offers "View a sample report", so this file is the first thing a
    visitor opens. `docs/web-compare.md` documents it as a copy of `examples/*_pdf_diff.html`;
    this pins that, so the sample cannot lag the example it is copied from.
    """
    served = hashlib.sha256(SERVED_SAMPLE.read_bytes()).hexdigest()
    example = hashlib.sha256(PDF_EXAMPLE.read_bytes()).hexdigest()
    assert served == example, (
        f"{SERVED_SAMPLE.relative_to(ROOT)} does not match {PDF_EXAMPLE.relative_to(ROOT)} "
        f"({served[:12]} vs {example[:12]}). {REGENERATE} Then copy it over the sample:\n"
        f"  cp {PDF_EXAMPLE.relative_to(ROOT)} {SERVED_SAMPLE.relative_to(ROOT)}"
    )
