"""The committed parser-validation report must match a fresh regeneration (#423).

`docs/parser-validation.md` is generated by `scripts/generate_validation_report.py` and
carries a do-not-edit-by-hand banner, but nothing checked that the committed copy is what
the generator actually emits. A hand-wrap in cc9fae1 made the two disagree: the
Legislative Branch bullet is built as a single f-string, so every regeneration flattened
it again, and anyone re-running the generator for a real change inherited a spurious
wrapping diff — or learned to `git checkout` the doc after generating, which is how
genuine numeric drift would get thrown away with the noise.

These tests regenerate into a tmpdir and byte-compare, the same shape as
`tests/test_committed_examples.py`. The render takes ~0.2s and reads only committed
fixtures (ADR 0015), so it runs UNMARKED in the default CI job rather than behind the
`slow` marker. That choice is load-bearing: CI invokes `slow` tests only by explicit
path (`.github/workflows/ci.yml`), so marking them `slow` would quietly drop them from
CI and rebuild the fail-open gap they exist to close (see `test_committed_examples.py`).
"""

from __future__ import annotations

import sys
from pathlib import Path

import scripts.generate_validation_report as report
from tests.validation_sources import JURISDICTIONS

ROOT = Path(__file__).resolve().parent.parent
COMMITTED = ROOT / "docs" / "parser-validation.md"

REGENERATE = "Run `uv run python scripts/generate_validation_report.py` and commit the result."


def _mismatch(committed: bytes, fresh: bytes) -> str | None:
    """None when identical; otherwise point at the first differing line/column.

    The comparison is byte-exact, not whitespace-normalized: the generator is
    deterministic, so a wrapping-only difference is drift too — it means someone
    edited the generated file by hand.
    """
    if committed == fresh:
        return None
    old = committed.decode().splitlines()
    new = fresh.decode().splitlines()
    for n, (a, b) in enumerate(zip(old, new), start=1):
        if a != b:
            diff_col = _first_diff_column(a, b)
            return (
                f"first differs at line {n}, column {diff_col}:\n"
                f"  committed: {_clip(a, diff_col)}\n"
                f"  fresh:     {_clip(b, diff_col)}"
            )
    return f"identical for {min(len(old), len(new))} lines, then lengths differ ({len(old)} vs {len(new)})"


def _first_diff_column(a: str, b: str) -> int:
    """Return the 0-based index of the first differing character."""
    limit = min(len(a), len(b))
    for i in range(limit):
        if a[i] != b[i]:
            return i
    return limit


def _clip(s: str, diff_col: int, width: int = 160) -> str:
    """Return a ~width window of ``s`` centred on ``diff_col``.

    An ellipsis prefix makes it obvious when the window does not start at
    column 0; an ellipsis suffix is added when it does not reach the end.
    """
    if len(s) <= width:
        return s
    half = width // 2
    if diff_col < half:
        start, end = 0, width
    else:
        start = diff_col - half
        end = diff_col + half
        if end > len(s):
            start = len(s) - width
            end = len(s)
    prefix = "..." if start > 0 else ""
    suffix = "..." if end < len(s) else ""
    return f"{prefix}{s[start:end]}{suffix}"


def test_validation_report_fixtures_are_committed():
    """Fail closed if an input goes missing, rather than reporting a misleading diff.

    The generator degrades when a fixture is absent (a "not fetched" bullet, a
    "jurisdictions skipped" comment), so a missing input would make the byte-compare
    below fail with a stale-report message for what is really a missing-fixture
    problem — the same fail-open shape `test_committed_examples.py` guards at its
    corpus check.
    """
    missing = [report.LEG_BRANCH_FIXTURE.relative_to(ROOT)] if not report.LEG_BRANCH_FIXTURE.exists() else []
    missing += [p.relative_to(ROOT) for j in JURISDICTIONS for p in (j.fixture_path, j.bill_xml_path) if not p.exists()]
    assert not missing, f"fixtures generate_validation_report.py needs are missing: {missing}"


def test_committed_validation_report_matches_a_fresh_regeneration(tmp_path, monkeypatch):
    """The committed `docs/parser-validation.md` is what the generator emits today."""
    # main() parses sys.argv (pytest's own argv would fail its parser) and writes to
    # report.OUTPUT — redirect both, or the test would overwrite the committed file it
    # is supposed to be checking.
    monkeypatch.setattr(sys, "argv", ["generate_validation_report.py"])
    fresh = tmp_path / "parser-validation.md"
    monkeypatch.setattr(report, "OUTPUT", fresh)
    report.main()

    assert fresh.exists(), "generate_validation_report.main() wrote nothing; the comparison below would vacuously pass"
    diff = _mismatch(COMMITTED.read_bytes(), fresh.read_bytes())
    assert diff is None, f"docs/parser-validation.md is stale. {REGENERATE}\n{diff}"


def test_validation_report_gate_can_fire():
    """The comparison above, proven against synthetic bad input (and a good one).

    The gate exists to catch future numeric drift in the committed report, so it has
    to be shown detecting exactly that — a gate nobody has seen fail is not a gate.
    """
    good = b"# Parser accuracy\n\n**Overall: 774 / 822 accounts recalled (94.2%).**\n"
    assert _mismatch(good, good) is None

    # Numeric drift: one recalled account lost. This is what the gate is for.
    drifted = good.replace(b"774 / 822", b"773 / 822")
    result = _mismatch(good, drifted)
    assert result is not None
    assert "first differs at line 3" in result

    # A hand-edit that only rewraps a line must fire too: the file is generated, so
    # any byte difference means it no longer matches what the generator emits.
    rewrapped = good.replace(b"accounts recalled (94.2%).", b"accounts\nrecalled (94.2%).")
    assert _mismatch(good, rewrapped) is not None

    # Truncation (at a line boundary, so the shared prefix matches) fires too,
    # with the lengths called out.
    result = _mismatch(good, b"# Parser accuracy\n\n")
    assert result is not None
    assert "lengths differ" in result


def test_mismatch_window_centres_on_first_diff_column():
    """A difference past the old 160-character truncation is still visible."""
    # Both strings share 170 leading "a"s, then differ at column 170, then share
    # another 200 "b"s. Total length is 409, mirroring the Legislative Branch
    # bullet that motivated the windowed output.
    shared = "a" * 170
    committed = (shared + "X" + "b" * 200).encode()
    fresh = (shared + "Y" + "b" * 200).encode()

    result = _mismatch(committed, fresh)

    assert result is not None
    assert "column 170" in result
    assert "X" in result
    assert "Y" in result
    # The window starts at column 90, so the output must announce that the
    # leading columns are omitted.
    assert "..." in result
