"""Generate docs/parser-validation.md — the team-facing parser-accuracy report.

Runs the committee-report validation and writes a Markdown page describing how the parser
is validated and what the current recall is. Numbers are generated (never hand-typed), so
the doc cannot drift. Regenerate after changing the parser, fixtures, or jurisdictions:

  uv run python scripts/generate_validation_report.py

Requires the bill XML for each jurisdiction present locally (gitignored; fetch with
`uv run python scripts/build_validation.py --fetch`).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tests.corpus_paths import DATA_DIR  # noqa: E402
from tests.validation_check import validate_jurisdiction  # noqa: E402
from tests.validation_sources import JURISDICTIONS  # noqa: E402

OUTPUT = Path("docs/parser-validation.md")
LEG_BRANCH_FIXTURE = DATA_DIR / "validation_leg_branch.json"


def _leg_branch_summary() -> str:
    # Committed since ADR 0015, so a clean clone has this. Degrade like the
    # JURISDICTIONS availability filter below rather than raising FileNotFoundError,
    # for the partial checkout where it is genuinely absent.
    if not LEG_BRANCH_FIXTURE.exists():
        return "- **Legislative Branch** — not fetched (run `uv run python scripts/build_validation.py --fetch`)."
    data = json.loads(LEG_BRANCH_FIXTURE.read_text())
    accounts = data["accounts"]
    bills = sorted({a["bill"] for a in accounts})
    chambers = sorted({a["chamber"] for a in accounts})
    return (
        f"- **Legislative Branch** — {len(accounts)} line items across {len(bills)} enrolled "
        f"bills ({', '.join(bills)}), chambers: {', '.join(chambers)}. Source: an independently "
        "maintained appropriations spreadsheet. Validated *structurally* (`TestLegBranchValidation`): "
        "each curated account names a `match_path`, and the parser must produce a node there with "
        "the expected amount."
    )


def build_parser() -> argparse.ArgumentParser:
    return argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)


def main() -> None:
    build_parser().parse_args()
    available = [j for j in JURISDICTIONS if j.fixture_path.exists() and j.bill_xml_path.exists()]
    missing = [j.slug for j in JURISDICTIONS if j not in available]

    rows, residual_sections, tot, val = [], [], 0, 0
    for j in available:
        results = validate_jurisdiction(j)
        unvalidated = [r for r in results if not r.validated]
        tot += len(results)
        val += len(results) - len(unvalidated)
        rate = 100 * (len(results) - len(unvalidated)) / len(results)
        rows.append(
            f"| {j.display} | `{j.bill_id}` | {len(results)} | {len(results) - len(unvalidated)} | {rate:.0f}% |"
        )
        if unvalidated:
            lines = "\n".join(f"  - {r.title or '—'} / {r.excel_name} — ${r.expected_amount:,}" for r in unvalidated)
            residual_sections.append(f"**{j.display}** ({len(unvalidated)})\n{lines}")

    overall = 100 * val / tot if tot else 0
    doc = f"""<!-- Generated by scripts/generate_validation_report.py. Do not edit by hand. -->

# Parser accuracy: how we validate it and why we trust it

This page explains how we check that the bill parser extracts dollar amounts correctly,
and what the current numbers are. It is generated from the validation suite, so the figures
here match the tests.

## Bottom line (for everyone)

Our tool reads each appropriations bill and pulls out the dollar amount for every account. To
confirm it reads them correctly, we compare its output against an **independent source we did
not build**: the committee report that Congress publishes alongside each bill. The bill and the
report are written separately, by different people, for different purposes — so when the tool's
numbers match the report, that is real, independent evidence the tool got it right.

Across **all 12 regular appropriations subcommittees**, the tool's amounts match the independent
source about **{overall:.0f}% of the time**. We then hand-checked every remaining case, and
**none is a tool error.** Each is a spot where the report and the bill legitimately state a
number differently — for example, the report gives one account total while the bill splits it
into separate lines, or the amount is open-ended ("such sums as may be necessary") so there is
no fixed figure in the bill to match. We also confirmed the tool is not just "tuned" to the
bills we happened to test (see *Guarding against overfitting* below).

The rest of this page is the detail behind that claim. Terms: the **parser** is the tool that
reads the bill; an **account** is one funding line (e.g. "FBI — Salaries and Expenses"); a match
is called a **recall**.

## What is being tested

The system under test is our **bill parser** (`bill_tree` / `diff_bill`) reading dollar
amounts out of the **bill XML** (the authoritative text from govinfo). We do not question the
bill XML; we check that our parser reads it correctly, by comparing the parser's output to
**independent ground truth**.

## Two independent ground-truth sources

{_leg_branch_summary()}
- **{len(available)} other jurisdictions** — committee-recommended amounts parsed from the
  Senate Appropriations **committee reports** (govinfo `CRPT-…`), compared to what the parser
  extracts from each reported bill. The report is written by committee staff for a different
  purpose than the bill, so it is genuinely independent. (Committee reports, not CRS reports.)
  Most are the FY2025 reported bills; two use an earlier year (the FY2024 CJS overfitting guard,
  and Homeland Security, whose FY2025 bill the Senate never reported) — see the table. Most are
  read from the report's 3-line summary blocks; **tabular** jurisdictions (Defense) print
  accounts only in the wide comparative statement, so those are read from that table instead
  (committee-recommendation column, converted from thousands to dollars).

An account is counted as **recalled** when the report's amount appears in the parser's
extraction under the correct agency, or as a sum of the account's components (totals the bill
states only as parts). See `tests/validation_check.py::validate_jurisdiction`. For the comparative-
statement source, rollup totals/subtotals and negative reduction/offset lines (rescissions,
offsetting collections) are excluded — they are not leaf appropriation accounts.

## Current recall (committee-report jurisdictions)

| Jurisdiction | Bill | Accounts | Recalled | Recall |
|---|---|---:|---:|---:|
{chr(10).join(rows)}

**Overall: {val} / {tot} accounts recalled ({overall:.1f}%).**

## Why the remainder is not a parser problem

Every unrecalled account below was traced by hand. None is a parser extraction error; each is
an inherent difference between how the *report* and the *bill* state a figure:

- **Indefinite "such sums" accounts** — the bill states no fixed dollar figure (e.g. Contract
  Support Costs, Payments for Tribal Leases, the Commodity Credit Corporation reimbursement).
  The report prints an estimate; there is nothing in the bill text to match.
- **Account totals the bill itemizes** — the report gives an account total, the bill states the
  components (e.g. HUD Tenant-Based Rental Assistance = renewals + a separate line). The single
  total never appears as one number in the bill, so there is nothing for the parser to match.
- **Report-side typos** — the report's own number is wrong (e.g. NASA Safety, Security and
  Mission Services: the report narrative prints the budget estimate, while the bill and the
  report's own comparative statement agree on the correct figure, which the parser extracts).
- **Shared account names** — sub-allocations under a name shared across bureaus
  ("Salaries and Expenses"), where the report's granularity differs from the bill's.

The full current remainder:

{chr(10).join(residual_sections) if residual_sections else "_(none)_"}

## Guarding against overfitting

The concern behind this work (GitHub #8) is that the parser's heuristics might be tuned to the
specific bills we happen to have. Three things push against that:

- **A different fiscal year.** The table above includes **Commerce-Justice-Science (FY2024)** —
  a bill and report not otherwise in our corpus. It recalls at the same rate as FY2025 CJS, with
  the same two structural misses, so the parser is not keyed to one year's formatting.
- **Both chambers.** The Legislative Branch source spans House and Senate enrolled bills across
  FY2014–FY2020. (The committee-report jurisdictions are Senate-only because House appropriations
  reports render their account tables as embedded images, so there is no text for the reader to
  extract — a limit of the *report source*, not the bill parser, which parses House bill XML fine.)
- **Many independent jurisdictions.** Every committee-report jurisdiction in the table above —
  spanning very different account structures (flat tabular Defense, deeply-nested Energy-Water,
  narrative summary blocks) — recalls in the same band, which is the opposite of what overfitting
  to one structure would produce.

## Honest limits

- This validates **amount extraction**, not the version-to-version **diff/comparison**, which
  is covered by separate hand-built fixtures.
- The committee-report check is internal-consistency between two documents of the same
  legislative process. It is strong for catching the parser misreading unfamiliar structure
  (which is the overfitting risk), but it is not a third-party audit.
- Coverage now spans all 12 regular Senate appropriations subcommittees: 11 via committee
  reports here (FY2025, except Homeland Security — the Senate never reported an FY2025 DHS
  bill, so its FY2024 reported bill is used instead) plus Legislative Branch via the
  spreadsheet source. Other years and the House chamber are not exhaustively covered.

## Reproduce

```bash
uv run python scripts/build_validation.py --fetch   # fetch sources, rebuild fixtures
uv run pytest tests/test_validate_extraction.py -m slow   # run the validation
uv run python scripts/generate_validation_report.py   # refresh this page
```
"""
    if missing:
        doc += f"\n<!-- jurisdictions skipped (bill XML not present locally): {', '.join(missing)} -->\n"

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(doc, encoding="utf-8")
    print(f"wrote {OUTPUT} ({val}/{tot} recalled, {overall:.1f}%); skipped: {missing or 'none'}")


if __name__ == "__main__":
    main()
